sudo: required
services:
  - docker
env:
  - global:
      - SHA = $(git rev-parse HEAD)
      - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-react-app
  - gcloud config set compute/zone asia-east1-a
  - gcloud container clusters get-credentials multi-k8s-react-app-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t hamza156/docker-react-app-test-image -f ./client/dockerfile.dev ./client
script:
  - docker run -e=CI=true hamza156/docker-react-app-test-image npm run test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master